### ISSUE TITLE
Create ReadMe.md

### ISSUE THREAD

**Issue by MorrisB--** [MorrisB--/MasterHash#1]
Need to create a ReadMe so new contributors know what is going on.

**Comment by krys2fa** [comment]
Hello @MorrisB, I would like to work on this. Kindly provide further instructions.

**Comment by MorrisB--** [comment]
Nice to meet you @krys2fa, and welcome to the team! MasterHash will is a password manager that allows a user to have an almost infinite amount of passwords while only using their main one. What will make this product different from others on the market is that it will all be stored in one encrypted file which will allow easy transport.

The software will be written mainly in Java, with the GUI written in JavaFX. The goal of the ReadMe should cover these things:

1. What the software is about, and what it accomplishes
2. How to get started (cloning the repo, launching the software, etc)
3. What to do if you find a bug, or have any issues
4. Guide to Contributing

None of this is set in stone, and I'd love to have all types of feedback. Let me know if you have any questions.

-Morris

**Comment by vhinmanansala** [comment]
Hello @MorrisB--  I'm interested on this as well.

**Comment by MorrisB--** [comment]
Nice to meet you @vhinmanansala, I'm not sure if @krys2fa started working on it yet, but I'm sure it won't be a problem if multiple people start working on it. Especially since the ReadMe will probably need to be refined constantly once development begins. If you have any questions feel free to ask!

-Morris

**Comment by krys2fa** [comment]
Hello @MorrisB-- , I've submitted a PR for review but like you said, @vhinmanansala can chip in once the review is done.

**Comment by MorrisB--** [comment]
Looks great to me @krys2fa! @vhinmanansala feel free to add as you see fit. For example we'll need to add how to set up the project in Eclipse (importing the project, etc.). So if you want to add that please feel free.

I'll be working on more tonight so the coding will start this week!
