### ISSUE TITLE
Add Gitter into the README.md

### ISSUE THREAD

**Issue by MorrisB--** [MorrisB--/MasterHash#12]
Consider adding Gitter for random chatting

**Comment by MorrisB--** [comment]
This should probably be added so we don't need to have random conversations in open or closed tickets.

**Comment by MorrisB--** [comment]
Here is the chat, if someone knows how to add one of those fancy buttons inside the README.md that would be awesome.

https://gitter.im/Master-Hash/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by Anirudh257** [comment]
I want to get assigned to this problem. You will have to add this in the readme.

**Comment by MorrisB--** [comment]
Hey @Anirudh257 feel free to tackle any of the issues, just remember to submit a pull request when it's done!

**Comment by srajappa** [comment]
Please review my PR :)
