### ISSUE TITLE
Update README.md to emphasize referencing when making a commit or pull request

### ISSUE THREAD

**Issue by MorrisB--** [MorrisB--/MasterHash#17]
![image](https://cloud.githubusercontent.com/assets/8133610/26276683/71075b88-3d41-11e7-8dc3-7fd91ff21d67.png)

This image doesn't need to be included but just in case the title doesn't make sense.

**Comment by Anirudh257** [comment]
Hey, @MorrisB-- I am a beginner and I would like to get assigned to this problem.

**Comment by MorrisB--** [comment]
Hey @Anirudh257 go right ahead! Just submit a pull request when you're done

**Comment by srajappa** [comment]
Please Review my PR :)

**Comment by MorrisB--** [comment]
Hey @srajappa I just merged it, looks wonderful thanks a lot!
