### ISSUE TITLE
Link to some good JavaFX tutorials in the README.md

### ISSUE THREAD

**Issue by MorrisB--** [MorrisB--/MasterHash#19]
Many newcomers may know how to use Java but have no clue how to use JavaFX. We should link to some good tutorials within the README.md

**Comment by MorrisB--** [comment]
I really like this one by TheNewBoston on YouTube, someone can add this if they'd like:

https://www.youtube.com/playlist?list=PL6gx4Cwl9DGBzfXLWLSYVy8EbTdpGbUIG

**Comment by jrod730** [comment]
I can take care of this!

**Comment by MorrisB--** [comment]
Hey @jrod730 sounds good and welcome! It's all yours!

**Comment by jrod730** [comment]
Thank you! Please let me know if there are any issues with my changes.

**Comment by MorrisB--** [comment]
@jrod730 Will do, just submit a pull request when you're ready.

**Comment by Anirudh257** [comment]
Check this one out. https://www.udemy.com/crash-course-into-javafx-the-best-way-to-make-gui-apps/
I have actually completed this course and it was very rewarding.

**Comment by MorrisB--** [comment]
Hey @Anirudh257 , that's a great one, if you want to add a section within the readme go right ahead!

Thanks,
Morris

**Comment by codemonger** [comment]
Hi, I've not contributed (without assistance) to an opensource project before.  I'm familiar with technical writing so I'd like to offer a solution for this issue.

**Comment by MorrisB--** [comment]
Thanks @codemonger for making it look much better!
