### ISSUE TITLE
Update STRUCTURE.md for Table.java

### ISSUE THREAD

**Issue by MorrisB--** [MorrisB--/MasterHash#24]
There is a new class, Table.java that needs to be added to STRUCTURE.md

**Comment by MorrisB--** [comment]
@rshbhdv is handling this issue.

**Comment by Anirudh257** [comment]
I can work on this too. Working on your project has been a great pleasure. Can I please get assigned on this?

**Comment by MorrisB--** [comment]
Hey @Anirudh257 I just merged this! Thanks for all the great work it's been really helpful!
