### ISSUE TITLE
Create NewLogin.java with some placeholders.

### ISSUE THREAD

**Issue by MorrisB--** [MorrisB--/MasterHash#26]
We need NewLogin.java to be created, but it doesn't need to be 100% completed. Just a couple of placeholders to start and get a feel of things. The only thing that is needed on the NewLogin page for now is the title, text fields, and a few buttons. This page will serve as a popup to Home.java, a mock up of the page can be seen below:

https://ninjamock.com/s/7ZGBV

Please note: Do not add any CSS or special styling, and do not edit any other classes. Please view the source code of Welcome.java and Home.java to get a feel of our coding standards.

**Comment by sapayth** [comment]
I am working on it
