### ISSUE TITLE
Link pages together

### ISSUE THREAD

**Issue by MorrisB--** [MorrisB--/MasterHash#34]
Now that all the rough drafts of the pages are created it's time to link them together. No special validation needs to be done. For example I click sign in and it opens Home.java. And if I click New Login it opens NewLogin.java.

**Comment by srajappa** [comment]
Can i work on it ?

**Comment by MorrisB--** [comment]
Hey @srajappa, yeah go right ahead!

**Comment by patanric** [comment]
@srajappa are you still working on it? If not I would have a solution.

**Comment by srajappa** [comment]
I worked on it yesterday. Don't think my solution worked, I am still interested in completing it :) 

But if you want to complete it quick, i will relinquish.

**Comment by patanric** [comment]
Don't worry give it another try if you like. May be your solution is better than mine. I will check tomorrow or sunday evening again if you fixed it.

**Comment by srajappa** [comment]
Thank you :)

**Comment by patanric** [comment]
Hi @srajappa , how are you progressing with this task? Do you need some help?

**Comment by MorrisB--** [comment]
Hey @patanric you can feel free to take a crack at it if you want, we can all just refine whatever code comes in.
