### ISSUE TITLE
Create structure.md

### ISSUE THREAD

**Issue by MorrisB--** [MorrisB--/MasterHash#4]
We need to create a file that explains to newcomers how the layout of the code works. This is just a very rough idea but the content of the file can read and look something like this for now and we can change it as we go:

```
com.MasterHash
	.gui - Contains all the screens
		Welcome.java - The main screen when the application is launched.
		Home.java - One the user is logged in they will be able all there logins
		NewLogin.java - Where the user can create new logins
	.security
		File.java - Used to generate a new file
		NewPassword.java - Used to generate new passwords for logins
		Decrypt.java - Used to decrypt the file
		Encrypt.java - Used to encrypt the file
```

There are a few things missing but won't matter until later, feel free to share opinions!

**Comment by TheRojam** [comment]
i could do this.

**Comment by MorrisB--** [comment]
Hey @TheRojam, I was traveling but I'm back now, feel free to take this one if you want!

**Comment by TheRojam** [comment]
@MorrisB-- everythings fine :) no matter :) i am trying to participate in a few projects.

**Comment by asv-hungvt** [comment]
Hello @MorrisB-- ,

How is this issue going?

**Comment by MorrisB--** [comment]
Hi @asv-hungvt nice to meet you! This issue is still open and available! If you'd like to take it feel free!

**Comment by asv-hungvt** [comment]
Hi @MorrisB-- 

Please instruct me what to do first. Thank you :)

**Comment by MorrisB--** [comment]
@asv-hungvt Sorry for the late response! I'm just looking for a document that looks kind of like the README.md, but has the data posted at the top of this ticket. It doesn't need to be word for word, and you can add as you see fit. Plus we can always revise as we go so no worries!

Thanks!

**Comment by asv-hungvt** [comment]
hello @MorrisB-- ,

I have pushed the file, Can you review it and feedback?

Thank you :D

**Comment by MorrisB--** [comment]
Hey @asv-hungvt this looks great! The only thing I would change is the name of the file. It's probably best to follow the all caps like the README.md. So the only change I would make it calling it STRUCTURE.md. But besides that it's fantastic!

Now all you'll need to do is submit a pull request so I can merge it to the main branch. Let me know if you need assistance and thanks again! I'll be working a lot on MasterHash in the coming weeks to be sure to keep an eye out!

**Comment by MorrisB--** [comment]
@asv-hungvt Actually I do see a typo on the Home.java bullet point. It should say 'Once' instead of 'One'

**Comment by asv-hungvt** [comment]
@MorrisB-- 

The PR is made. 

I also would like to join to your project, can you consider what can I help?

Cheer!

**Comment by MorrisB--** [comment]
@asv-hungvt I just merged it! 

Are you familiar with Java, JavaFX, or encryption? That would be really helpful. I plan on having a Pre-Alpha checklist soon, but eventually we'll need a logo and a CSS pro to make everything look nice!

**Comment by asv-hungvt** [comment]
I am familiar with Java and basic encryption. I think it will be nice to take part in this project :D

**Comment by MorrisB--** [comment]
@asv-hungvt Awesome! Just give me the weekend and I'll have a bunch of new tasks! I've been busier than expected but the Pre-Alpha tasklist is almost done!

**Comment by asv-hungvt** [comment]
OK sure :D
