### ISSUE TITLE
Enhance "Getting Started" part of README.md to guide users on how to import project to Eclipse.

### ISSUE THREAD

**Issue by MorrisB--** [MorrisB--/MasterHash#5]
Doesn't have to be too detailed, maybe a simple link to something that shows new people where to download eclipse and how to import the project.

**Comment by griffste** [comment]
@MorrisB-- Hello I am looking to make my first Open Source contribution. I'd like to claim this if it is still available? Do I just need to add two links - one to download eclipse and one showing how to import the project to eclipse - to the README?

**Comment by griffste** [comment]
@MorrisB-- I submitted a pull request for this. Please let me know if there is anything I can change or improve.

**Comment by MorrisB--** [comment]
Hello @griffste!

I just merged your request it looks great! However now that I look at it what do you think about combining the Getting Started and Eclipse section, since they're pretty similar? Let me know if you have any other suggestions!

Thanks,
Morris

**Comment by griffste** [comment]
@MorrisB-- Sure I can combine them, whatever you think is best. I'll work on a new pull request now.

**Comment by griffste** [comment]
@MorrisB-- Let me know if you think this new pull request is better. I tried numbering the parts after "To Import to Eclipse" as 3 and 4, but markdown automatically switches them to 1 and 2 with the statement in between. If you want I can take out "To import..." statement and just have all four steps in a row. Just thought some people might use the code right on Git, so it would be better kind of separated. Let me know what you think

https://github.com/MorrisB--/MasterHash/pull/10

**Comment by MorrisB--** [comment]
@griffste  Looks great! Very well considered thanks for completing this!
